# ============================================================
#  NYKAA (FSN E-Commerce) — Full Python EDA & Analysis Script
#  Dataset : Screener.in export  |  All values in ₹ Crore
# ============================================================

# -------------------------------------------------------
# STEP 0 — IMPORTS
# -------------------------------------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Set a clean, dark style for all plots
plt.rcParams.update({
    'figure.facecolor': '#1a1a2e',
    'axes.facecolor':   '#16213e',
    'axes.edgecolor':   '#0f3460',
    'axes.labelcolor':  'white',
    'xtick.color':      'white',
    'ytick.color':      'white',
    'text.color':       'white',
    'grid.color':       '#0f3460',
    'grid.linestyle':   '--',
    'grid.alpha':       0.5,
    'legend.facecolor': '#16213e',
    'legend.edgecolor': '#0f3460',
    'font.family':      'DejaVu Sans',
})
PALETTE = ['#e94560', '#0f3460', '#533483', '#05c46b', '#ffd460']


# -------------------------------------------------------
# STEP 1 — LOAD DATA
# -------------------------------------------------------
# We use the pre-cleaned CSVs (generated by the extraction script).
# Each CSV represents one financial statement.

pl = pd.read_csv('data/profit_loss.csv')
bs = pd.read_csv('data/balance_sheet.csv')
cf = pd.read_csv('data/cash_flow.csv')
qt = pd.read_csv('data/quarters.csv')

print("=" * 60)
print("  NYKAA FINANCIAL DATA — LOADED SUCCESSFULLY")
print("=" * 60)
print(f"\nP&L rows   : {len(pl)} years  | Columns: {list(pl.columns)}")
print(f"Balance    : {len(bs)} years  | Columns: {list(bs.columns)}")
print(f"Cash Flow  : {len(cf)} years  | Columns: {list(cf.columns)}")
print(f"Quarters   : {len(qt)} qtrs   | Columns: {list(qt.columns)}")


# -------------------------------------------------------
# STEP 2 — BASIC EXPLORATION (df.head / df.info / describe)
# -------------------------------------------------------
print("\n\n--- P&L Head ---")
print(pl.head())

print("\n--- P&L Data Types & Missing ---")
print(pl.info())

print("\n--- P&L Descriptive Stats ---")
print(pl.describe().round(2))


# -------------------------------------------------------
# STEP 3 — DATA CLEANING
# -------------------------------------------------------
# Fill NaN values with 0 (e.g. Other_Expenses missing for some years)
# In financial data, NaN usually means the item didn't exist that year
pl.fillna(0, inplace=True)
bs.fillna(0, inplace=True)
cf.fillna(0, inplace=True)
qt.fillna(0, inplace=True)

# Ensure Year is treated as string (categorical, not integer)
pl['Year'] = pl['Year'].astype(str)
bs['Year'] = bs['Year'].astype(str)
cf['Year'] = cf['Year'].astype(str)

print("\n--- After Cleaning: P&L Missing Values ---")
print(pl.isnull().sum())


# -------------------------------------------------------
# STEP 4 — FEATURE ENGINEERING (Derived KPIs)
# -------------------------------------------------------
# These are the key ratios every analyst computes. We derive them
# directly from the raw financials so the dashboard can use them.

# --- Profit & Loss Ratios ---
pl['Total_Expenses'] = (
    pl['Raw_Material_Cost'] + pl['Change_in_Inventory'] +
    pl['Power_and_Fuel'] + pl['Other_Mfr_Exp'] +
    pl['Employee_Cost'] + pl['Selling_and_Admin'] +
    pl['Other_Expenses']
)
pl['Operating_Profit'] = pl['Sales'] - pl['Total_Expenses']

# Gross Margin = (Sales - COGS) / Sales × 100
# COGS = Raw Material + Inventory change + Mfr Exp
pl['COGS'] = pl['Raw_Material_Cost'] + pl['Change_in_Inventory'] + pl['Other_Mfr_Exp']
pl['Gross_Margin_Pct'] = ((pl['Sales'] - pl['COGS']) / pl['Sales'] * 100).round(2)

# OPM = Operating Profit / Sales × 100
pl['OPM_Pct'] = (pl['Operating_Profit'] / pl['Sales'] * 100).round(2)

# Net Profit Margin = Net Profit / Sales × 100
pl['NPM_Pct'] = (pl['Net_profit'] / pl['Sales'] * 100).round(2)

# Revenue Growth YoY %
pl['Revenue_Growth_Pct'] = pl['Sales'].pct_change() * 100
pl['Revenue_Growth_Pct'] = pl['Revenue_Growth_Pct'].round(2)

# --- Balance Sheet Ratios ---
bs['Total_Equity'] = bs['Equity_Share_Capital'] + bs['Reserves']
bs['Debt_to_Equity'] = (bs['Borrowings'] / bs['Total_Equity']).round(2)
bs['Current_Ratio']  = (bs['Receivables'] + bs['Inventory'] + bs['Cash_and_Bank']) / bs['Other_Liabilities']
bs['Current_Ratio']  = bs['Current_Ratio'].round(2)

# --- Merged Master Table (Annual) ---
master = pl.merge(bs, on='Year').merge(cf, on='Year')
master['ROE_Pct']  = (master['Net_profit'] / master['Total_Equity'] * 100).round(2)
master['ROCE_Pct'] = (master['Profit_before_tax'] / master['Total_Assets'] * 100).round(2)

print("\n--- Engineered KPIs (P&L) ---")
print(pl[['Year','Sales','Gross_Margin_Pct','OPM_Pct','NPM_Pct','Revenue_Growth_Pct']])

print("\n--- Balance Sheet Ratios ---")
print(bs[['Year','Debt_to_Equity','Current_Ratio','Total_Equity']])

print("\n--- Master Table Profitability ---")
print(master[['Year','ROE_Pct','ROCE_Pct']])


# -------------------------------------------------------
# STEP 5 — SAVE ENRICHED CSVs FOR POWER BI / SQL
# -------------------------------------------------------
pl.to_csv('data/profit_loss_enriched.csv', index=False)
bs.to_csv('data/balance_sheet_enriched.csv', index=False)
cf.to_csv('data/cash_flow_enriched.csv', index=False)
master.to_csv('data/master_annual.csv', index=False)
qt.to_csv('data/quarters_clean.csv', index=False)
print("\n✅ Enriched CSVs saved to data/ folder.")


# -------------------------------------------------------
# STEP 6 — VISUALIZATIONS (5 charts)
# -------------------------------------------------------

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Nykaa (FSN E-Commerce) — Financial Dashboard', fontsize=18, fontweight='bold', color='white', y=1.01)
fig.patch.set_facecolor('#1a1a2e')
axes = axes.flatten()

# --- Chart 1: Revenue Trend ---
ax = axes[0]
ax.plot(pl['Year'], pl['Sales'], marker='o', color='#e94560', linewidth=2.5, markersize=7)
ax.fill_between(pl['Year'], pl['Sales'], alpha=0.15, color='#e94560')
ax.set_title('Revenue Trend (₹ Cr)', fontweight='bold')
ax.set_xlabel('Year'); ax.set_ylabel('₹ Crore')
ax.grid(True, alpha=0.3)
for i, (x, y) in enumerate(zip(pl['Year'], pl['Sales'])):
    ax.annotate(f'₹{y:.0f}', (x, y), textcoords='offset points', xytext=(0,8), fontsize=7.5, ha='center', color='white')

# --- Chart 2: Margin Waterfall ---
ax = axes[1]
margins = ['Gross\nMargin', 'Operating\nMargin (OPM)', 'Net Profit\nMargin']
latest = pl.iloc[-1]
vals = [latest['Gross_Margin_Pct'], latest['OPM_Pct'], latest['NPM_Pct']]
colors = ['#05c46b' if v > 0 else '#e94560' for v in vals]
bars = ax.bar(margins, vals, color=colors, edgecolor='white', linewidth=0.5, width=0.5)
ax.axhline(0, color='white', linewidth=0.8, linestyle='--')
ax.set_title(f'Margin Waterfall — FY{pl["Year"].iloc[-1]}', fontweight='bold')
ax.set_ylabel('Margin %')
for bar, val in zip(bars, vals):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + (1 if val > 0 else -3),
            f'{val:.1f}%', ha='center', va='bottom', fontweight='bold', color='white')

# --- Chart 3: Margin % Over Years ---
ax = axes[2]
ax.plot(pl['Year'], pl['Gross_Margin_Pct'], marker='s', label='Gross Margin', color='#05c46b', linewidth=2)
ax.plot(pl['Year'], pl['OPM_Pct'],          marker='^', label='OPM',          color='#ffd460', linewidth=2)
ax.plot(pl['Year'], pl['NPM_Pct'],          marker='o', label='Net Margin',   color='#e94560', linewidth=2)
ax.axhline(0, color='white', linewidth=0.7, linestyle='--')
ax.set_title('Margin Trends Over Years (%)', fontweight='bold')
ax.set_ylabel('%'); ax.legend(fontsize=8)
ax.grid(True, alpha=0.3)

# --- Chart 4: Debt-to-Equity Ratio ---
ax = axes[3]
colors_de = ['#e94560' if v > 0.3 else '#05c46b' for v in bs['Debt_to_Equity']]
ax.bar(bs['Year'], bs['Debt_to_Equity'], color=colors_de, edgecolor='white', linewidth=0.5)
ax.set_title('Debt-to-Equity Ratio', fontweight='bold')
ax.set_ylabel('D/E Ratio'); ax.set_xlabel('Year')
ax.axhline(0.3, color='#ffd460', linewidth=1.2, linestyle='--', label='0.3 Safe Zone')
ax.legend(fontsize=8)
ax.grid(True, alpha=0.3)

# --- Chart 5: Cash vs Profit ---
ax = axes[4]
x = np.arange(len(master))
width = 0.35
ax.bar(x - width/2, master['Net_profit'],          width, label='Net Profit',         color='#533483')
ax.bar(x + width/2, master['Cash_from_Operations'], width, label='Operating Cash Flow', color='#0f3460')
ax.set_xticks(x); ax.set_xticklabels(master['Year'], rotation=45)
ax.set_title('Cash Flow vs Net Profit (₹ Cr)', fontweight='bold')
ax.set_ylabel('₹ Crore'); ax.legend(fontsize=8)
ax.axhline(0, color='white', linewidth=0.7, linestyle='--')
ax.grid(True, alpha=0.3)

# Hide 6th subplot (unused)
axes[5].set_visible(False)

plt.tight_layout()
plt.savefig('data/nykaa_dashboard.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
plt.show()
print("\n✅ Dashboard saved as data/nykaa_dashboard.png")


# -------------------------------------------------------
# STEP 7 — QUARTERLY TREND (Bonus Chart)
# -------------------------------------------------------
fig2, ax2 = plt.subplots(figsize=(14, 5))
fig2.patch.set_facecolor('#1a1a2e')
ax2.set_facecolor('#16213e')
ax2.plot(qt['Quarter'], qt['Sales'],     marker='o', color='#e94560', linewidth=2, label='Sales')
ax2.plot(qt['Quarter'], qt['Net_profit'],marker='s', color='#05c46b', linewidth=2, label='Net Profit')
ax2.axhline(0, color='white', linewidth=0.7, linestyle='--')
ax2.set_title('Quarterly Sales vs Net Profit (₹ Cr)', fontweight='bold', color='white', fontsize=13)
ax2.set_xlabel('Quarter', color='white')
ax2.set_ylabel('₹ Crore', color='white')
ax2.legend()
ax2.grid(True, alpha=0.3)
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig('data/quarterly_trend.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
plt.show()
print("✅ Quarterly chart saved as data/quarterly_trend.png")

print("\n\n✅ ALL STEPS COMPLETE — Data is ready for SQL & Power BI!")
